### ISSUE TITLE
 'HomeBroker' object has no attribute 'orders'

### ISSUE THREAD

**Issue by davidcer** [crapher/pyhomebroker#10]
Hola Diego,
Estoy replicando el ejemplo de github y obtengo este mensaje al intentar detectar ordenes activas en home broker. ¿tiene sentido?

orders = hb.orders.get_orders_status(account_id)
AttributeError: 'HomeBroker' object has no attribute 'orders'

Muchas gracias,

David

**Comment by crapher** [comment]
Asegurate de tener la ultima version 0.4.
