### ISSUE TITLE
Cuando te suscribís a un orderbook da error.

### ISSUE THREAD

**Issue by rodrialbanese** [crapher/pyhomebroker#13]
Usando el ejemplo otorgado, después de traer la primer info de la suscripción da un error.
por ejemplo:

hb.online.subscribe_order_book('AL30', '48hs')
te trae 
------------------ Order Book (Level 2) ------------------
                            bid_size     bid  bid_offers_count  ask_size     ask  ask_offers_count
symbol settlement position
AL30   48hs       1            84020  6058.0                 2     85045  6059.0                 2
                  2            16064  6056.5                 2     61792  6059.5                 3
                  3              408  6056.0                 2     67103  6060.0                 6
                  4            59015  6055.5                 3       200  6061.0                 1
                  5             5988  6055.0                10     50000  6061.5                 1

pero luego da error.
Si imprimís la exception en la función que agarra los errores sale 'NoneType' object is not iterable.

**Comment by martinnmayer** [comment]
Me esta pasando lo mismo. Lo pudiste solucionar?

**Comment by crapher** [comment]
Ayer corregi y subi al Github la correccion de ese problema.
Como a mi no me pasa no tengo forma de probarlo por eso no lo subi a Pypi todavia hasta que alguien me confirme que funciona.

Prueben instalandolo desde Github.

**pip install git+https://github.com/crapher/pyhomebroker --upgrade --no-cache-dir**

**Comment by martinnmayer** [comment]
Segui tus instrucciones y ahora me funciona perfecto! Mil gracias

**Comment by rodrialbanese** [comment]
Lo mismo digo, ahora funciona bien.
Mañana sigo probando. Tenés algún canal para hacerte consultas que no sea por acá (así no abro un Issue por una simple consulta)?. Laburazo tremendo btw.
