### ISSUE TITLE
Consulta de último precio sin sucripción

### ISSUE THREAD

**Issue by rodrialbanese** [crapher/pyhomebroker#15]
Martín, te hago una consulta. Hay alguna forma de tomar el último precio (u otro dato del book) de un activo en especial sin tener que hacer una suscripción online? Por ejemplo quiero saber último precio y volumen de CECO2, pero necesito eso solo y no que se vaya actualizando. Se puede hacer?

**Comment by crapher** [comment]
No hay formaa de obtener las puntas salvo por suscripcion (para evitar que se haga pooling y colapse el server del broker), para el resto de la informacion (OHLCV y algunos otros datos) fijate en este ejemplo.

https://github.com/crapher/pyhomebroker/blob/main/examples/example_market_snapshot.py
