### ISSUE TITLE
Mapping en columnas "turnover" y "volume"

### ISSUE THREAD

**Issue by roldan** [crapher/pyhomebroker#17]
Hola, antes que nada gracias por el gran laburo que hay en este repo! más que útil!
Esto más que un issue es una consulta (que tal vez sea un pequeño bug):
Estaba viendo el ejemplo de "get_market_snapshot" y no estoy seguro de que los valores de las columnas "turnover" y "volume" sean los correctos. Parece como que estuviesen invertidas. Por lo que veo, "turnover" está tomando el valor de "TotalAmountTraded" (que es el monto total operado en pesos) y "volume" de "TotalQuantityTraded". Esto es correcto? No debería estar tomándose "TotalAmountTraded" en volume? 

Saludos y gracias!

**Comment by crapher** [comment]
Es correcto como esta. Volume es la cantidad de papeles operados, turnover es la cantidad de moneda operada (pesos o dolares dependiendo del instrumento)

**Comment by roldan** [comment]
perfecto @crapher gracias por la aclaración!
