### ISSUE TITLE
Warning asyncio

### ISSUE THREAD

**Issue by juanledes** [crapher/pyhomebroker#19]
Warning (from warnings module):
  File "C:\Users\***\***\pyhomebroker\main_HM.py", line 100
    loop = asyncio.get_event_loop()
DeprecationWarning: There is no current event loop

Al actualizar a python 3.10 me salta este warning, al parecer la planilla sigue actualizando normalmente.

**Comment by crapher** [comment]
Ese error no es de pyhomebroker fijate que esta en main_HM.py que no es parte de la libreria.  
Incluso me parece que ese deprecation warning es del asyncio.
