### ISSUE TITLE
Empty data frame

### ISSUE THREAD

**Issue by herfedo** [crapher/pyhomebroker#2]
Probe con BCCH y PSEC, este ultimo al consulta datos historicos me trae:

Empty DataFrame
Columns: [date, open, high, low, close, volume]

Utilizando el mismo programa, solo cambiando los datos de login, decime si te puedo pasar alguna datos mas, desde la pagina puedo consultar el historico.

**Comment by herfedo** [comment]
Estas son las url generadas para probar la primera devuelve el dataframe vacio, la otro funciona:

https://operar.psec.com.ar/HistoricoPrecios/history?symbol=GGAL&resolution=D&from=1420070400&to=1577836800

https://clientes.bcch.org.ar/HistoricoPrecios/history?symbol=GGAL&resolution=D&from=1420070400&to=1577836800

**Comment by crapher** [comment]
Si en la pagina le das click para ver un grafico, te muestra el grafico?  
En caso que te lo muestre, en chrome dale click derecho sobre la ventana y despues el menu inspeccionar.  
Anda a la parte de redes (Network) y refresca la ventana.
Abri nuevamente el grafico y en busca en redes alguna entrada que diga HistoricoPrecios y pegame la direccion please.

**Comment by herfedo** [comment]
Decime si esto te sirve, la version de hb es 1.6.4:

![image](https://user-images.githubusercontent.com/44303147/96588531-24781a80-12ba-11eb-9ac9-1f443a4d8bf2.png)

**Comment by crapher** [comment]
Nope... este seria.
En portafolio online y click en el iconito ese.

<img width="1206" alt="Screen Shot 2020-10-20 at 9 25 00 AM" src="https://user-images.githubusercontent.com/10857655/96600189-4d96ac00-12b6-11eb-80d0-8bb52fa56386.png">

**Comment by herfedo** [comment]
Ahí me fije y no tiene esa opción PSEC, te abre el grafico vacío y solo muestra el botón de intradiario, pero no muestra información tampoco, será por la versión de homebroker ? En PSEC es la 1.6.4 y en BCCH funciona bien y encuentro la opción me que indicas, y es la versión 1.7.0

Es PSEC para ver los precio históricos tenes que ir a la opción Histórico de Precios del menú Precios, ingresar fecha desde y hasta y la especie.

**Comment by automaishon** [comment]
Ejemplo de hoy

URL= https://operar.psec.com.ar/Intradiario/history?symbol=GGAL&resolution=1&from=1603323279&to=1603323879

Saludos

**Comment by crapher** [comment]
No esta soportado por la version instalada en el agente.
