### ISSUE TITLE
ALFY error al conectar

### ISSUE THREAD

**Issue by gerarg** [crapher/pyhomebroker#20]
Cuando intento hacer hb.online.connect() después de loguearme me tira:

WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request

Con cocos funciona perfecto usando el mismo código

**Comment by crapher** [comment]
Estoy viendo que la pagina de los hubs de signalR que retorna es correcta y es igual a la de Cocos.

No tengo cuenta en Alfy para hacer debugging.  Te hago un par de consultas:
- Chequeaste que la pagina de precios de HomeBroker funcione correctamente en Alfy?
- No te falla nada en el login? Si falla algo en el login el signalR no funciona.
- Cuando hacer el connect, te retorna alguna informacion o solo esa excepcion?

**Comment by gerarg** [comment]
- El homebroker de Alfy funciona perfecto, esto me viene pasando desde el viernes que lo intenté por primera vez con Alfy y como me saltó ese error pensé que hoy a las 11 se iba a solucionar pero no.

- El login no tiene ningún problema, las veces que le puse mal el usuario o la contraseña a propósito para probar si era eso me tiró la exception correspondiente.

- Solo me tira esa excepción, a mi también me parece raro porque estuve tratando de debuggear un rato y las url parecían estar bien.

**Comment by agennaro1** [comment]
> Cuando intento hacer hb.online.connect() después de loguearme me tira:
> 
> WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers) websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request
> 
> Con cocos funciona perfecto usando el mismo código

Lo seguis usando con Cocos???? entiendo que el ususario es el email , correcto?

**Comment by gerarg** [comment]
> Lo seguis usando con Cocos???? entiendo que el ususario es el email , correcto?

Hace mucho que no lo uso la verdad, terminé haciendo una especie de scrapper a mano porque los otros no me servían mucho, de todas formas te recomiendo que no uses la cuenta de Cocos (si es con la que operás) porque te la pueden bloquear

**Comment by crapher** [comment]
Cierro este ticket porque no tengo informacion para poder resolverlo y no se si aun es valido.
Cualquier cosa si hay algo de informacion adicional o sigue pasando abranlo de nuevo.
