### ISSUE TITLE
Suscribirse al estado de las órdenes en curso

### ISSUE THREAD

**Issue by agustin2021** [crapher/pyhomebroker#21]
Buenas tardes, espero se encuentren muy bien.

Quisiera consultarles si hay manera de recibir una notificación del servidor cada vez que una orden en curso cambie de estado, esto es,  sea cancelada, ejecutada total o parcialmente.

Muchas gracias.
Saludos

**Comment by crapher** [comment]
Lamentablemente Homebroker no envia esa informacion por subscripcion al signalR.  
La unica forma que hay para hacerlo es haciendo pooling y preguntando el estado de las ordenes cada X tiempo.
