### ISSUE TITLE
Plazos de Bonos y Acciones "CI" 

### ISSUE THREAD

**Issue by merinodiego** [crapher/pyhomebroker#26]
Hola, estuve probando el tema de las ordenes anda muy bien.
Ahora si queres trabajar en otros plazos como CI, como quedaria el Ticker por ejemplo para un GD30? "GD30 CI" para armar la pregunta en el #Get Intra day Information y en el plazo del BUY

order_number = hb.orders.send_buy_order('GD30D', 'C.I.', 36.381, 1) ??

Saludos, Gracias.

**Comment by crapher** [comment]
Hola,

Para contado inmediato deberias usar **spot**
Para 24hs deberias usar **24hs**
Para 48hs deberias usar **48hs**

Igualmente, para poder operar Contado Inmediato desde homebroker el broker te lo tiene que activar.  Por default, no se puede operar contado inmediato segun tengo entendido.

Slds

**Comment by hoomany** [comment]
Buenas!
Hay forma de obtener data intraday de los activos en CI ?
Mi broker, COCOS tiene permitido operar en CI , pero no  aparece opcion alguna de info intraday en la web del homebroker  .
Analizando la pag web llegue al mismo endpoint que emplea pyhomebroker.
https://cocoscap.com/Intradiario/history?symbol=GD30&resolution=1&from=1681154925&to=1681155525

Existe algun workarround para tener info intraday?
Muchas gracias. (espero que este comment no abra el issue)
