### ISSUE TITLE
Incorporar datos a evento opciones

### ISSUE THREAD

**Issue by leonardorame** [crapher/pyhomebroker#4]
Diego, en el evento `on_options`, ¿se podrá incorporar el Subyacente y el Strike?. Con esos datos sería mas fácil filtrar por las opciones de GGAL por ej y armar una tablita de sintéticas donde tengamos el CALL y el PUT en la misma fila, similar a esta:

![image](https://user-images.githubusercontent.com/1405017/96629705-5c975180-12ea-11eb-883d-737ddf8e6762.png)

**Comment by leonardorame** [comment]
Veo que el Strike está, lo único que quedaría es el subyacente, pero por ahora puedo filtrarlo.

**Comment by crapher** [comment]
Ya esta subido el cambio al GitHub.  
Podes instalarte la version de GitHub que ya tiene el underlying_asset.
