### ISSUE TITLE
Caller is not authorized to invoke the JoinGroup method on StockPricesHub.

### ISSUE THREAD

**Issue by leonardorame** [crapher/pyhomebroker#5]
Diego, está dando ese error al querer conectarme:

`Caller is not authorized to invoke the JoinGroup method on StockPricesHub.`

**Comment by crapher** [comment]
Ya quedo resuelto en la version 0.1.1
Tambien subi la version a pypi por lo que se puede instalar con 

**pip install pyhomebroker --upgrade --no-cache-dir**
