### ISSUE TITLE
Sobre panel de opciones

### ISSUE THREAD

**Issue by leonardorame** [crapher/pyhomebroker#8]
Sería importante aclarar en la documentación que la función `on_options=on_options_callback` trae los tickers registrados en Favoritos.

P.d.: Estoy usando el pythomebroker a full, una masa, felicitaciones.

**Comment by crapher** [comment]
Esto no es asi la funcion on_options trae el panel de opciones.  Si no trae el panel de opciones, hay un error. (hay que ver que HB no este trayendo lo mismo)
Si tenes un ejemplo para reproducir este error o el error resuelto por favor reabri este ticket y agrega el ejemplo asi lo resolvemos.

**Comment by leonardorame** [comment]
Mirá, copio sólo la parte relevante del código:

```
def on_open(online):   
    print('=================== CONNECTION OPENED ====================')

def optionsfn(online, quotes):
    print(quotes)

def on_error(online, error):
    print('@@@@@@@@@@@@@@@@@@@@@@@@@ Error @@@@@@@@@@@@@@@@@@@@@@@@@@')
    print(error)

def on_close(online):
    print('=================== CONNECTION CLOSED ====================')

hb = HomeBroker(int(broker), 
    on_open=on_open, 
    on_personal_portfolio=None, 
    on_securities=None, 
    on_options=optionsfn, 
    on_repos=None, 
    on_order_book=None, 
    on_error=on_error, 
    on_close=on_close)

hb.auth.login(dni=dni, user=user, password=password, raise_exception=True)

hb.online.connect()

hb.online.subscribe_personal_portfolio()
hb.online.subscribe_options
```
Al ejecutarlo sólo me imprime:
```
============= CONNECTION OPENED =============
```

**Comment by leonardorame** [comment]
Olvidate!!!, me faltaron los paréntesis, funciona perfecto.
