### ISSUE TITLE
Delay/Ticks perdidos entre Gallo y Rodi

### ISSUE THREAD

**Issue by leonardorame** [crapher/pyhomebroker#9]
Hola Diego, estoy comparando los ticks que van entrando a Pyhomebroker y comparándolos contra Rodi. Noté que hay un cierto delay y en muchos casos datos que nunca llegan, siempre RODI tiene información más actualizada.

¿Vos encontraste las mismas diferencias?. Desconozco si la instancia de Gallo es la misma para todos los brokers, en mi caso uso TM.

Seguramente esto no es un problema de PyhomeBroker, sino de Gallo, pero quería consultarte esto para sacarme la duda.

Datos tomados alas 13:12

## Rodi

![image](https://user-images.githubusercontent.com/1405017/99415444-8c7c4980-28d6-11eb-9bb8-f0e9cfae2be9.png)

## PyhomeBroker

![image](https://user-images.githubusercontent.com/1405017/99415516-a322a080-28d6-11eb-858c-f4a09b76868a.png)

**Comment by crapher** [comment]
Yo le creo mas a HB que a Rodi.  Normalmente Rodi esta muy atrasado respecto a HB.
Para chequear el atraso abri el nivel 2 de rodi y comparalo con HB.

**Comment by leonardorame** [comment]
Sí, lo hice así. Pero puse la captura de PanelPersonal porque ahí se muestra la hora de la operación.

**Comment by crapher** [comment]
Estas tomando el tiempo que tarda en hacer la insercion esa que tenes ahi o el codigo que haces cuando se dispara el evento?

Agrega al principio del metodo un
```
ts = time.time()
```

y al final
```
print(time.time() - ts)
```
para ver cuanto tarda.

Quiza es una acumulacion de pequeños tiempos que generan ese delay... (Igualmente se que HB no funciona bien siempre y a veces se cuelga y hasta te desconecta sin aviso)
En cuando al panel personal de Rodi no le doy bola porque normalmente es un desastre. (Lo unico que vale en el Rodi es el Nivel2)
